### ISSUE TITLE
initialization fails

### ISSUE THREAD

**Issue by klak2** [unicap/aroio-ng#1]
My initialization fails:

[16:56:56] kkadmin@ak-2c1600:/usr/src/aroio> git clone --recurse-submodules https://github.com/unicap/aroio-ng.git
Klone nach 'aroio-ng' ...
remote: Enumerating objects: 862, done.
remote: Counting objects: 100% (862/862), done.
remote: Compressing objects: 100% (373/373), done.
remote: Total 2578 (delta 506), reused 703 (delta 370), pack-reused 1716
Empfange Objekte: 100% (2578/2578), 91.70 MiB | 3.11 MiB/s, Fertig.
Löse Unterschiede auf: 100% (1248/1248), Fertig.
Submodul 'buildroot' (https://github.com/unicap/audiostreamer-buildroot.git) für Pfad 'buildroot' in die Konfiguration eingetragen.
Klone nach '/usr/src/aroio/aroio-ng/buildroot' ...
remote: Enumerating objects: 56, done.        
remote: Counting objects: 100% (56/56), done.        
remote: Compressing objects: 100% (44/44), done.        
remote: Total 269424 (delta 21), reused 34 (delta 12), pack-reused 269368        
Empfange Objekte: 100% (269424/269424), 100.60 MiB | 3.12 MiB/s, Fertig.
Löse Unterschiede auf: 100% (184813/184813), Fertig.
error: Der Server lehnt Anfrage nach nicht angebotenem Objekt 56013b05fce6abd00b27b2651eee72a34f561628 ab.
"fetch" in Submodul-Pfad 'buildroot' ausgeführt, aber 56013b05fce6abd00b27b2651eee72a34f561628 nicht
enthalten. Direktes Anfordern dieses Commits ist fehlgeschlagen.

Where is my problem?

Greets klak

**Comment by TIS-Arne** [comment]
@mr-berndt 
Nico: Sieht so aus als hättest Du vergessen, den buildroot-Ordner zu pushen.

**Comment by klak2** [comment]
Hi,
habe absolut keinen Schimmer von git usw. Bin bisher nach der Anletung der Startseite vorgegangen und bisher funktionierte das so.

Was muss ich wo tun?

Dank und Gruss
klak

**Comment by klak2** [comment]
Bin eigentlich nur hier gelandet, weil die 4er Version noch keine Custom-Overlays kann und ich drei kleine Ergaenzungen fuer mich gerne haette.

**Comment by TIS-Arne** [comment]
@klak2 
Du kannst da im Moment gar nix machen. Der Kollege hat vergessen, sein Repository hochzuladen, deshalb kommt es zu dieser Fehlermeldung.

**Comment by klak2** [comment]
Danke für die Info.

**Comment by unicap** [comment]
@klak2 
Das Repository sollte jetzt wieder in Ordnung sein, kannst es nochmal probieren.

**Comment by klak2** [comment]
Hi,

`Löse Unterschiede auf: 100% (5910019/5910019), Fertig.
Checke Dateien aus: 100% (62275/62275), Fertig.
Could not fetch special ref '6dabe04c82943c34fb5bcadc9cc2ee7b6b4a145b'; assuming it is not special.
fatal: Referenz ist kein "Tree"-Objekt: 6dabe04c82943c34fb5bcadc9cc2ee7b6b4a145b
--2019-04-30 20:40:44--  http://sources.buildroot.net/linux-6dabe04c82943c34fb5bcadc9cc2ee7b6b4a145b.tar.gz
Auflösen des Hostnamens proxy.universum.all (proxy.universum.all)… 192.168.100.157
Verbindungsaufbau zu proxy.universum.all (proxy.universum.all)|192.168.100.157|:3128 … verbunden.
Proxy-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2019-04-30 20:40:44 FEHLER 404: Not Found.

make[1]: *** [package/pkg-generic.mk:148: /10_output/aroio/build/linux-6dabe04c82943c34fb5bcadc9cc2ee7b6b4a145b/.stamp_downloaded] Fehler 1
make: *** [Makefile:16: _all] Fehler 2
` 
Scheint noch etwas andere zu fehlen. Oder?

**Comment by mr-berndt** [comment]
Das ist ja seltsam, denn ich habe das nach dem Reparieren des Repos direkt noch mal komplett frisch ausgechecked, um es zu testen. Das lief anstandlos durch.

@unicap 
Arne, könntest Du das noch mal bei Dir testen?

**Comment by unicap** [comment]
@mr-berndt 
Der Fehler oben passiert nicht beim Auschecken, sondern beim Bauen. Ich kann das gerade nicht ausprobieren, kannst Du das bei Dir testen?

**Comment by mr-berndt** [comment]
Stimmt, hatte ich übersehen. Ich hatte nur auf 'Löse Unterschiede auf' geguckt und dachte, das würde beim Auschecken passieren.

Der Hash da ist der Commit des verwendeten Kernels. Warum da probiert wird, den von sources.buildroot.net zu holen, ist mir nicht klar. Evtl. ist das eine Rückfall-Adresse, falls die aus dem .mk File nicht erreichbar ist?

Wie dem auch sei, ich bau das mal eben, wird einen Moment dauern, und dann melde ich mich zurück.

**Comment by mr-berndt** [comment]
Kurze Rückmeldung: Ist noch in Arbeit, gestaltet sich etwas aufwändiger, als gedacht..

**Comment by mr-berndt** [comment]
So, der Fehler ist behoben. Bitte einmal im Ordner "aroio" "git pull" und dann im Ausgabeordner "make aroio_defconfig" ausführen. Danach sollte es bauen. Wir haben beim Testen festgestellt, dass auf dem Hostrecher sowohl "flex" als auch "libssl-dev" installiert sein müssen. Viel Erfolg!

**Comment by klak2** [comment]
Hi,

"make" lief wieder durch. Dank an euch.
