### ISSUE TITLE
Pause-Taste(n) keine Funktion 

### ISSUE THREAD

**Issue by klak2** [unicap/aroio-ng#2]
Hi,
kleiner Hinweis: 
Habe einen PreAmp14, bei dem funktionieren die Pausentasten [A/|>] , sowohl am Geraet als auch an der FB nicht. 

Habe einmal mit meinen Aenderungen und einmal ohne meine Aenderungen gebaut, beide Male keine Funktion.

VG klak2

ps: Beim ONLINE direkt update (4.15.53) Pause OK.

**Comment by mr-berndt** [comment]
Ich habe es einmal frisch ausgechecked und gebaut und die Tasten an einem PreAmp14 funktionieren bei mir. Könntest Du mir vtl. mal die Logs herunterladen und schicken? Am einfachsten als PN im Abacus-Forum oder hier per Link.

**Comment by klak2** [comment]
Auf einer anderen Kiste nochmal gebaut - jetzt funktioniert die  PauseTaste. Staun.
Dank fuer die Muehe.
