### ISSUE TITLE
http://www.ludd.luth.se/~torger/files/brutefir-1.0m.tar.gz

### ISSUE THREAD

**Issue by klak2** [unicap/aroio-ng#3]
wget -4 http://www.ludd.luth.se/~torger/files/brutefir-1.0m.tar.gz

--2019-07-21 23:01:58--  http://www.ludd.luth.se/~torger/files/brutefir-1.0m.tar.gz
Auflösen des Hostnamens www.ludd.luth.se (www.ludd.luth.se)… 130.240.16.10
Verbindungsaufbau zu www.ludd.luth.se (www.ludd.luth.se)|130.240.16.10|:80 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 301 Moved Permanently
Platz: https://www.ludd.ltu.se/~torger/files/brutefir-1.0m.tar.gz [folgend]
--2019-07-21 23:01:58--  https://www.ludd.ltu.se/~torger/files/brutefir-1.0m.tar.gz
Auflösen des Hostnamens www.ludd.ltu.se (www.ludd.ltu.se)… 130.240.16.10
Verbindungsaufbau zu www.ludd.ltu.se (www.ludd.ltu.se)|130.240.16.10|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 503 Service Unavailable
2019-07-21 23:01:58 FEHLER 503: Service Unavailable.

Datei mindestens seit 14 Tagen nicht verfügbar.

**Comment by mr-berndt** [comment]
??!?

Was genau willst Du uns nun sagen?

What exactly are you meaning to tell us?

**Comment by klak2** [comment]
Der Build scheitert, weil die obige Datei seit mindestens 14 Tagen nicht mehr unter der URL im Betreff verfügbar ist.

**Comment by klak2** [comment]
[06:57:51] kkadmin@ak-2c1600:/usr/src/aroio> head  ./aroio-ng/aroio/package/brutefir/brutefir.mk
################################################################################
#
# brutefir
#
################################################################################

BRUTEFIR_VERSION = 1.0m
BRUTEFIR_SOURCE = brutefir-$(BRUTEFIR_VERSION).tar.gz
BRUTEFIR_SITE = http://www.ludd.luth.se/~torger/files
BRUTEFIR_LICENSE = GPLv2

**Comment by mr-berndt** [comment]
Ich tippe da mal auf ein temporäres Server-Problem, da die Seite bei einem Institut gehosted ist, das komplett down ist. LUDD - Luleå Academic Computer Society - LTU

Ich kann morgen mal gucken, ob ich da näheres zu rausfinde oder eine alternative URL. Auf die Schnelle finde ich leider nix.

**Comment by mr-berndt** [comment]
Ich hatte die Leute, die das hosten zwischendurch mal angeschrieben und die Seite ist auch wieder da. Ob das zusammenhängt, weiß ich nicht, jedenfalls geht alles wieder.

**Comment by klak2** [comment]
Dank für alles.
