### ISSUE TITLE
Problem with make order

### ISSUE THREAD

**Issue by willdebut** [unicap/aroio-ng#4]
Hello, 
when I try the make command I get the following error that occurs:

mv: cannot stat '/mnt/h/output_test/aroio/build/glibc-glibc-2.26-107-g73a92363619e52c458146e903dfb9b1ba823aa40/build/debug/stamp.osT': No such file or directory
make[4]: *** [../o-iterator.mk:9: /mnt/h/output_test/aroio/build/glibc-glibc-2.26-107-g73a92363619e52c458146e903dfb9b1ba823aa40/build/debug/stamp.os] Error 1
make[3]: *** [Makefile:215: debug/subdir_lib] Error 2
make[2]: *** [Makefile:9: all] Error 2
make[1]: *** [package/pkg-generic.mk:237: /mnt/h/output_test/aroio/build/glibc-glibc-2.26-107-g73a92363619e52c458146e903dfb9b1ba823aa40/.stamp_built] Error 2
make: *** [Makefile:16: _all] Error 2

Cordially

Translated with www.DeepL.com/Translator

**Comment by cal0pteryx** [comment]
Please re-open if this issue persists while using a current version.
